name = "SpineInterface"
uuid = "0cda1612-498a-11e9-3c92-77fa82595a4f"
authors = ["Spine Project consortium <spine_info@vtt.fi>"]
version = "0.3.5"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Suppressor = "fd094767-a336-5f1f-9728-57cf17d0bbfb"
